### PR TITLE
fix: handle single error responses

### LINKED ISSUE #47: v0.6.0 not working
As mentioned in https://github.com/knocklabs/knock-node/pull/44, `v0.6.0` gives us the following error:

```
[TypeError: errors is not iterable]
```

when running the following operation:

```js
await knock.workflows.updateSchedules({
  data: { todoId, timeZone },
  schedule_ids: [dateStartReminder.scheduleId],
  scheduled_at: new Date(dateStart)
})
```

### PR DESCRIPTION
**Pull request by connorlindsey**
## Description

The API typically returns an array of error messages but in some cases, returns a single error. This update checks if errors is an array or single instance. If it's a single error, it wraps it in an array so that formatting the error message works correctly in `UnprocessableEntityException`

Resolves #47

### CODE REVIEW

File: src/knock.ts [hunk 1]
```diff
@@ -172,7 +172,10 @@ class Knock {
           throw new BadRequestException(code, message, requestID);
         }
         case 422: {
-          const { errors } = data;
+          const errors = Array.isArray(data.errors)
+            ? data.errors
+            : [data.errors];
```
Comment (cjbell) [inline src/knock.ts:177]: If errors is null or undefined, then won't this end up as `[null]`?

Comment (connorlindsey) [reply src/knock.ts:180]: Good call, added an extra check if errors is not defined

**Review by cjbell — APPROVED** [review]
💯
